---
- name: Install MySQL database server
  hosts: mydb-server
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    mysql_root_password: 'rootpwd'
    mysql_pocuser_password: 'Password@1'
  tasks:
    - name: Update the software package repository
      apt:
        name: "*"
        update_cache: yes

    - name: Install MySQL
      package:
        name: mysql-server
        state: present

    - name: Install MySQL client
      package:
        name: mysql-client
        state: present

    - name: Install python mysqldb
      package:
        name: python3-mysqldb
        state: latest

    - name: Update root password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: root
        host: "{{ hostvars['mydb-server'].ansible_host }}"
        password: "{{ mysql_root_password }}"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
  
    - name: Delete anonymous MySQL user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ""
        host: "{{ hostvars['mydb-server'].ansible_host }}"
        state: absent
      with_items:
        - localhost
        - "{{ hostvars['mydb-server'].ansible_host }}"

    - name: Delete Hostname based MySQL user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ""
        host: "{{ hostvars['mydb-server'].ansible_host }}"
        state: absent

    - name: Remove MySQL test database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: test
        state: absent

    - name: enable UFW
      ufw:
        state: enabled
        policy: allow

    - name: Start mysql
      service:
        name: mysql
        state: restarted

    - name: Enable mysql
      service:
        name: mysql
        enabled: yes
 
    - name: Change bind address
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^bind-address(.+)127.0.0.1"
        replace: "bind-address=0.0.0.0"

    - name: Restart mysql service
      service:
        name: mysql
        state: restarted

    - name: Create a user with name pocuser
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: pocuser
        host: localhost
        password: "{{ mysql_pocuser_password }}"
        priv: '*.*:ALL'
        state: present

    - name: create a user with name pocuser with mydb-server host
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: pocuser
        host: "{{ hostvars['myweb-server'].ansible_host }}"
        password: "{{ mysql_pocuser_password }}"
        priv: '*.*:ALL'
        state: present

    - name: Create a new database
      mysql_db:
        login_user: pocuser
        login_password: "{{ mysql_pocuser_password }}"
        name: pocdb
        state: present

    - name: Copy the SQL file to create pocusers table
      copy:
        src: ./pocusers.sql
        dest: /tmp/pocusers.sql

    - name: Create the pocusers table
      mysql_db:
        login_user: pocuser
        login_password: "{{ mysql_pocuser_password }}"
        name: pocdb
        state: import
        target: /tmp/pocusers.sql
...
