---
- name: Install MySQL database server
  hosts: mydb-server
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    mysql_root_password: 'root'
    mysql_demo_password: 'demo'
  tasks:
    - name: Update the software package repository
      apt:
        name: "*"
        update_cache: yes

    - name: Install MySQL
      package:
        name: mysql-server
        state: present

    - name: Install MySQL client
      package:
        name: mysql-client
        state: present

    - name: Install python mysqldb
      package:
        name: python3-mysqldb
        state: latest

    - name: Update root password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: root
        host: mydb-server
        password: "{{ mysql_root_password }}"
  
    - name: Delete anonymous MySQL user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ""
        host: mydb-server
        state: absent

    - name: Delete Hostname based MySQL user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ""
        host: mydb-server
        state: absent

    - name: Remove MySQL test database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: test
        state: absent

    - name: enable UFW
      ufw:
        state: enabled
        policy: allow

    - name: Start mysql
      service:
        name: mysql
        state: restarted

    - name: Enable mysql
      service:
        name: mysql
        enabled: yes
 
    - name: Change bind address
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^bind-address(.+)127.0.0.1"
        replace: "bind-address=0.0.0.0"

    - name: Restart mysql service
      service:
        name: mysql
        state: restarted

    - name: Create a user with name demo
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: demo
        host: localhost
        password: "{{ mysql_demo_password }}"
        priv: '*.*:ALL'
        state: present

    - name: create a user with name demo with mydb-server host
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: demo
        host: mydb-server
        password: "{{ mysql_demo_password }}"
        priv: '*.*:ALL'
        state: present

    - name: Create a new database
      mysql_db:
        login_user: demo
        login_password: "{{ mysql_demo_password }}"
        name: mydatabase
        state: present

    - name: Copy the SQL file to create demousers table
      copy:
        src: ./demousers.sql
        dest: /tmp/demousers.sql

    - name: Create the demousers table
      mysql_db:
        login_user: demo
        login_password: "{{ mysql_demo_password }}"
        name: mydatabase
        state: import
        target: /tmp/demousers.sql
...
